steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/hw5spmhiremathsneha/flasktestservice', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/hw5spmhiremathsneha/flasktestservice']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '$PROJECTNAME', '--image', 'gcr.io/hw5spmhiremathsneha/flasktestservice', '--region', 'us-central1', '--platform', 'managed','--port','80']
images:
- gcr.io/hw5spmhiremathsneha/flasktestservice
